// tschap19/react/reactapp/src/App.tsx
import React, { Component } from 'react';
//import { Product, Order } from './data/entities';
//import { ProductList } from './productList';
import { dataStore } from "./data/dataStore";
import { Provider } from 'react-redux';
import { HttpHandler } from "./data/httpHandler";
import { addProduct } from './data/actionCreators';
import { ConnectedProductList } from './data/productListConnector';

interface Props {
    // no props required
}

export default class App extends Component<Props> {
    private httpHandler = new HttpHandler();

    constructor(props: Props) {
        super(props);
        this.httpHandler.loadProducts(data =>
            dataStore.dispatch(addProduct(...data)));
    }

    render = () =>
        <div className="App">
            <Provider store={ dataStore }>
                <ConnectedProductList />
            </Provider>
        </div>

    submitCallback = () => {
        console.log("Submit order");
    }
}

// tschap22/vue/vieapp/src/App.vue
<template>
  <ProductList />
</template>

<script lang="ts">
  import { Component, Prop, Vue } from "vue-property-decorator";
  import ProductList from "./views/ProductList.vue";
  import { HttpHandler } from "./data/httpHandler";
  import { action } from './data/storeDecorators';
  import { Product } from './data/entities';
  @Component({
    components: {
      ProductList
    }
  })
  export default class App extends Vue {
    private handler = new HttpHandler();
    constructor() {
      super();
      this.loadProducts(this.handler.loadProducts);
    }
    @action()
    loadProducts(task: () => Promise<Product[]>) {}
  }
</script>
